on:
  workflow_dispatch:

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.14.7

      - name: Terraform Init
        working-directory: ./.github/config/ceramic-aws-node
        run: terraform init

      - name: Terrafom Apply
        working-directory: ./.github/config/ceramic-aws-node
        # run: terraform -chdir=${{ github.workspace }} apply -auto-approve
        run: terraform -chdir=${{ github.workspace }} apply -auto-approve
        env:
          TF_VAR_ceramic_bucket_name: ${{ github.repository }}/ceramic-bucket
          TF_VAR_ipfs_bucket_name: ${{ github.repository }}/ipfs-bucket
      # run ansible playbook
