name: AWS Ceramic Infrastructure
on:
  workflow_dispatch:
    inputs:
      ceramic-network:
        description: "Ceramic network to deploy to"
        required: true
        default: "testnet-clay"
        type: choice
        options:
          - testnet-clay
          - mainnet
          - testnet-devel

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      REPO_SHA: ${{ github.sha }}
      WORKSPACE: ${{ github.workspace }}/.github/config/ceramic-aws-node
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.14.7

      - name: Terraform Init
        working-directory: ./.github/config/ceramic-aws-node
        run: terraform -chdir=$WORKSPACE init

      - name: Terrafom Apply
        working-directory: ./.github/config/ceramic-aws-node
        # run: terraform -chdir=${{ github.workspace }} apply -auto-approve
        run: terraform -chdir=$WORKSPACE apply -auto-approve
        env:
          TF_VAR_ceramic_bucket_name: $REPO_SHA-ceramic-bucket
          TF_VAR_ipfs_bucket_name: $REPO_SHA-ipfs-bucket
          TF_VAR_ceramic_network: ${{ inputs.ceramic-network }}
          TF_VAR_ansible_public_key: ${{ secrets.ANSIBLE_PUBLIC_KEY }}

      # run ansible playbook
