on:
  workflow_dispatch:

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      REPO_NAME: ${{ github.repository }}
      WORKSPACE: ${{ github.workspace }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.14.7

      - name: Terraform Init
        working-directory: ./.github/config/ceramic-aws-node
        run: terraform init

      - name: Terrafom Apply
        working-directory: ./.github/config/ceramic-aws-node
        # run: terraform -chdir=${{ github.workspace }} apply -auto-approve
        run: terraform -chdir=$WORKSPACE apply -auto-approve
        env:
          TF_VAR_ceramic_bucket_name: $REPO_NAME/ceramic-bucket
          TF_VAR_ipfs_bucket_name: $REPO_NAME/ipfs-bucket

      # run ansible playbook
